### ISSUE TITLE
Server configuration update

### ISSUE THREAD

**Issue by hiwelo** [VC4Africa/services-website-template#4]
Hi @billz 

In order to prepare the launching of the services website of VC4A, is it possible to update the configuration on the server for this website?

Here's the points:
- [ ] change the configuration from vc4a.services to services.vc4a.com
- [ ] create a 301 redirection for all request from vc4a.services to services.vc4a.com
- [ ] set the DNS of services.vc4a.com to target our production server
- [ ] create a SSL certificate for services.vc4a.com

Once it'll be done, I'll change the WordPress configuration to launch the website :)
Are you available to do these updates?
(We would like to launch the website Tuesday, if you're available to do these updates before)

**Comment by billz** [comment]
Couple of questions... 

1. Is this repo up to date? https://github.com/VC4Africa/services-website-template
Deploying with git is preferable.
2. Any db to replicate or is this a static website?

**Comment by billz** [comment]
The certificate for vc4a.com is GeoTrust QuickSSL Premium which includes 4 subdomains (api, secure, developers, www). Unfortunately, we can't modify these or add the extra subdomain 'services' until the certificate expires in April 17, 2017. After this date I'll change us over to a LetsEncrypt certificate which gives us greater flexibility. 

The upshot is services.vc4a.com cannot be under SSL for now. The domain variant vc4a.services can, however. Or we host services.* as non-SSL enabled.

**Comment by hiwelo** [comment]
Here some answer for your questions:

The repository template is up to date, but it's only for the theme. As you can see now on the staging server the template is already deployed with git.
For the complete WordPress installation, please ask @xoref who did the setup on the staging server and who know which is the database used by this WordPress.

**Comment by billz** [comment]
Ok, how about the SSL issue?

**Comment by hiwelo** [comment]
If you cannot add a specific LetsEncrypt just for services.vc4a.com, we can see with @catherineVC4A if we can wait until April 17 :)

**Comment by hiwelo** [comment]
For me, we can wait with a HTTP only until April 17, 2017 and use HTTPS after this date

**Comment by billz** [comment]
Yeah, certificates don't work that way :) Subdomains are added to an existing cert. Agreed, HTTP is fine for now

**Comment by catherineVC4A** [comment]
Yes, HTTP is fine for now

**Comment by billz** [comment]
One big downside to hosting a non-SSL subdomain is that it requires disabling HTTP Strict Transport Security (HSTS) for vc4a.com. 

More info: https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/

**Comment by catherineVC4A** [comment]
From an SEO standpoint, the lack of HSTS is not a show-stopper. What are the other risks and how big are they?

**Comment by billz** [comment]
Risks are described in the second paragraph of the link I provided.

**Comment by catherineVC4A** [comment]
Okay, given what I'm guessing to be the habits of and risks to our VC4A.com user base, I prefer to keep HSTS in place on vc4a.com and wait until April 17 to host the Services site on services.vc4a.com.

**Comment by billz** [comment]
Agreed. It's on the calendar.

**Comment by billz** [comment]
Deployed to production
